const CACHE='mistra-fiske-1.2.1';
const SHELL=["/", "/index.html", "/style.css?v=1.2.1", "/model.js?v=1.2.1", "/app.js?v=1.2.1", "/river-points.js?v=1.2.1", "/manifest.webmanifest", "/icon.svg", "/icon-192.png", "/icon-512.png", "/data/mistra.json", "/data/lures.json", "/api/guide", "/vendor/leaflet/leaflet.js", "/vendor/leaflet/leaflet.css", "/vendor/leaflet/images/marker-icon.png", "/vendor/leaflet/images/marker-shadow.png", "/lures/brown-minnow.jpg", "/lures/copper-spoon.jpg", "/lures/copper-streamer.jpg", "/lures/dark-spinner.jpg", "/lures/firetiger-vibration.jpg", "/lures/gold-crank.jpg", "/lures/gold-minnow.jpg", "/lures/gold-spinner.jpg", "/lures/orange-spoon.jpg", "/lures/perch-crank.jpg", "/lures/perch-natural.jpg", "/lures/pink-crank.jpg", "/lures/silver-minnow.jpg", "/lures/silver-spinner.jpg", "/lures/silver-spoon.jpg", "/lures/trout-crank.jpg", "/lures/trout-minnow.jpg", "/lures/white-streamer.jpg"];
self.addEventListener('install',event=>{event.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.allSettled(SHELL.map(async url=>{const r=await fetch(url);if(r.ok)await c.put(url,r);}));await self.skipWaiting();})());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith('mistra-fiske-')&&k!==CACHE)await caches.delete(k);await self.clients.claim();})());});
self.addEventListener('fetch',event=>{const u=new URL(event.request.url);if(event.request.method!=='GET'||u.origin!==self.location.origin)return;
 if(u.pathname.startsWith('/api/')&&u.pathname!=='/api/guide')return;
 if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).then(async r=>{if(r.ok)(await caches.open(CACHE)).put('/index.html',r.clone());return r;}).catch(()=>caches.match('/index.html')));return;}
 event.respondWith(caches.match(event.request).then(r=>r||fetch(event.request).then(async x=>{if(x.ok)(await caches.open(CACHE)).put(event.request,x.clone());return x;})));
});
